# Quick build - just fix and build
Write-Host "Quick APK build..." -ForegroundColor Green

# Fix the plugin file immediately
$pluginFile = "android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java"
$content = @"
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    // Plugin registration handled automatically by Flutter
  }
}
"@
Set-Content $pluginFile $content
Write-Host "Plugin file fixed." -ForegroundColor Green

# Build
Write-Host "Building..." -ForegroundColor Yellow
Set-Location android
.\gradlew assembleDebug
Set-Location ..

Write-Host "✅ Done! APK at: android\app\build\outputs\flutter-apk\app-debug.apk" -ForegroundColor Green